import type { GameSource } from "../types";

export const darkSouls3: GameSource = {
	gameName: "Dark Souls III",
	remarkPool: [
		"Bad roll timing",
		"Greedy extra hit",
		"Poise broke",
		"Backstab whiffed",
		"Fell off the edge",
		"Ganked by adds",
		"Ran out of estus",
		"Parry timing off",
	],
	groupTitlePool: ["Boss Rush", "Cinder Trials", "No-Estus Run"],
	profilePool: [
		{ name: "First Playthrough" },
		{ name: "Deprived Run" },
		{ name: "New Game Plus" },
		{ name: "Speedrun Attempt" },
		{ name: "Co-op Run" },
		{ name: "Pyromancer Build" },
	],
	subjectPool: [
		{ name: "Iudex Gundyr", context: "Boss" },
		{ name: "Vordt of the Boreal Valley", context: "Boss" },
		{ name: "Abyss Watchers", context: "Boss" },
		{ name: "Yhorm the Giant", context: "Boss" },
		{ name: "Aldrich, Devourer of Gods", context: "Boss" },
		{ name: "Pontiff Sulyvahn", context: "Boss" },
		{ name: "Dancer of the Boreal Valley", context: "Boss" },
		{ name: "Dragonslayer Armour", context: "Boss" },
		{ name: "Champion Gundyr", context: "Boss" },
		{ name: "Twin Princes", context: "Boss" },
		{ name: "Soul of Cinder", context: "Boss" },
		{ name: "Nameless King", context: "Boss" },
		{ name: "Darkeater Midir", context: "Boss" },
		{ name: "Slave Knight Gael", context: "Boss" },
		{ name: "Sister Friede", context: "Boss" },
		{ name: "Crystal Sage", context: "Mini Boss" },
		{ name: "Old Demon King", context: "Mini Boss" },
		{
			name: "Silver Knights",
			context: "Generic Enemy",
			reoccurring: true,
		},
		{
			name: "Hollow Soldiers",
			context: "Generic Enemy",
			reoccurring: true,
		},
		{ name: "Farron Keep", context: "Location" },
		{ name: "Irithyll", context: "Location" },
		{ name: "Catacombs of Carthus", context: "Location" },
	],
};
