import type { GameSource } from "../types";

export const eldenRing: GameSource = {
	gameName: "Elden Ring",
	remarkPool: [
		"Gravity combo got me",
		"Bad roll timing",
		"Greedy extra hit",
		"Poise broke",
		"Waterfowl dance",
		"Got gravity'd",
		"Fell off the cliff",
		"Ganked by adds",
		"Ran out of flasks",
		"Scadutree too low",
	],
	groupTitlePool: [
		"Boss Rush",
		"Remembrance Hunt",
		"Legacy Dungeon Sweep",
		"No-Flask Challenge",
		"Shadow Realm Bosses",
	],
	profilePool: [
		{ name: "First Playthrough" },
		{ name: "Strength Build" },
		{ name: "New Game Plus" },
		{ name: "Speedrun Attempt" },
		{ name: "Co-op Run" },
		{ name: "Solo Deathless Attempt" },
		{ name: "Shadow of the Erdtree" },
	],
	subjectPool: [
		{ name: "Margit, the Fell Omen", context: "Boss" },
		{ name: "Godrick the Grafted", context: "Boss" },
		{ name: "Rennala", context: "Boss" },
		{ name: "Radahn", context: "Boss" },
		{ name: "Morgott, the Omen King", context: "Boss" },
		{ name: "Fire Giant", context: "Boss" },
		{ name: "Malenia, Blade of Miquella", context: "Boss" },
		{ name: "Caelid Overworld", context: "Location" },
		{ name: "Nokstella", context: "Location" },
		{
			name: "Godskin Apostles",
			context: "Generic Enemy",
			reoccurring: true,
		},
		{ name: "Crucible Knight Ordovis", context: "Mini Boss" },
		{ name: "Leonine Misbegotten", context: "Mini Boss" },
		{ name: "Astel, Naturalborn of the Void", context: "Boss" },
		{ name: "Maliketh, the Black Blade", context: "Boss" },
		{ name: "Mohg, Lord of Blood", context: "Boss" },
		{ name: "Radahn, Consort of Miquella", context: "Boss" },
		{
			name: "Ancient Dragon Knights",
			context: "Generic Enemy",
			reoccurring: true,
		},
		{ name: "Tree Sentinel", context: "Mini Boss" },
		{ name: "Bell Bearing Hunter", context: "Mini Boss" },
		{ name: "Night's Cavalry", context: "Mini Boss" },
		{ name: "Ulcerated Tree Spirit", context: "Boss" },
		{ name: "Runebear", context: "Mini Boss" },
		{ name: "Erdtree Avatar", context: "Boss" },
		{ name: "Cemetery Shade", context: "Mini Boss" },
		{
			name: "Stonedigger Troll",
			context: "Generic Enemy",
			reoccurring: true,
		},
		{ name: "Land Octopus", context: "Generic Enemy", reoccurring: true },
		{
			name: "Wandering Noble",
			context: "Generic Enemy",
			reoccurring: true,
		},
		{ name: "Limgrave Overworld", context: "Location" },
		{ name: "Liurnia of the Lakes", context: "Location" },
		{ name: "Rellana, Twin Moon Knight", context: "Boss" },
		{ name: "Messmer the Impaler", context: "Boss" },
		{ name: "Romina, Saint of the Bud", context: "Boss" },
		{ name: "Metyr, Mother of Fingers", context: "Boss" },
		{ name: "Bayle the Dread", context: "Boss" },
		{ name: "Promised Consort Radahn", context: "Boss" },
	],
};
