import type { GameSource } from "../types";

export const hollowKnight: GameSource = {
	gameName: "Hollow Knight",
	remarkPool: [
		"Got greedy on heal",
		"Missed the dash",
		"Bad pogo timing",
		"Fell into spikes",
		"Bad soul management",
		"Second phase got me",
		"Mismanaged charms",
	],
	groupTitlePool: ["Pantheon Prep", "Charm-less Trial", "Speed Nail Run"],
	profilePool: [
		{ name: "Main Save" },
		{ name: "Steel Soul Run" },
		{ name: "New Save Slot" },
		{ name: "Speedrun Attempt" },
		{ name: "Randomizer Seed" },
		{ name: "God Rush Practice" },
	],
	subjectPool: [
		{ name: "False Knight", context: "Boss" },
		{ name: "Hornet Protector", context: "Boss" },
		{ name: "Broken Vessel", context: "Boss" },
		{ name: "Soul Master", context: "Boss" },
		{ name: "Watcher Knights", context: "Boss" },
		{ name: "Traitor Lord", context: "Mini Boss" },
		{ name: "The Radiance", context: "Boss" },
		{ name: "Deepnest", context: "Location" },
		{
			name: "Mantis Warriors",
			context: "Generic Enemy",
			reoccurring: true,
		},
		{ name: "Nightmare King Grimm", context: "Boss" },
		{ name: "Pure Vessel", context: "Boss" },
		{ name: "Absolute Radiance", context: "Boss" },
		{ name: "Pantheon of Hallownest", context: "Location" },
		{ name: "Zote the Mighty", context: "Other" },
		{ name: "Vengefly King", context: "Mini Boss" },
		{ name: "Massive Moss Charger", context: "Mini Boss" },
		{ name: "Brooding Mawlek", context: "Boss" },
		{ name: "Dung Defender", context: "Boss" },
		{ name: "Flukemarm", context: "Boss" },
		{ name: "Grey Prince Zote", context: "Boss" },
		{ name: "Hive Knight", context: "Boss" },
		{ name: "Uumuu", context: "Mini Boss" },
		{ name: "Winged Nosk", context: "Mini Boss" },
		{
			name: "Sisters of Battle",
			context: "Generic Enemy",
			reoccurring: true,
		},
		{ name: "Crystal Peak", context: "Location" },
		{ name: "Greenpath", context: "Location" },
	],
};
