import type { GameSource } from "../types";

export const sekiro: GameSource = {
	gameName: "Sekiro",
	remarkPool: [
		"Failed the deflect",
		"Posture broke first",
		"Missed the mikiri",
		"Greedy extra swing",
		"Fell off the ledge",
		"Bad dodge read",
		"Phase 2 spike got me",
	],
	groupTitlePool: ["Deathblow Gauntlet", "No-Heal Trial", "Boss Rush"],
	profilePool: [
		{ name: "Wolf's Path" },
		{ name: "Charmless Run" },
		{ name: "New Game Plus" },
		{ name: "Speedrun Attempt" },
		{ name: "Bell Demon Run" },
		{ name: "Practice Sword Grave" },
	],
	subjectPool: [
		{ name: "Gyoubu Oniwa", context: "Boss" },
		{ name: "Lady Butterfly", context: "Boss" },
		{ name: "Genichiro Ashina", context: "Boss" },
		{ name: "Guardian Ape", context: "Boss" },
		{ name: "Corrupted Monk", context: "Boss" },
		{ name: "Great Shinobi Owl", context: "Boss" },
		{ name: "Isshin, the Sword Saint", context: "Boss" },
		{ name: "Ashina Castle", context: "Location" },
		{
			name: "Ashina Elite Samurai",
			context: "Generic Enemy",
			reoccurring: true,
		},
		{ name: "Juzou the Drunkard", context: "Mini Boss" },
		{ name: "Snake Eyes Shirafuji", context: "Mini Boss" },
		{ name: "Demon of Hatred", context: "Boss" },
		{ name: "Owl (Father)", context: "Boss" },
		{ name: "Chained Ogre", context: "Mini Boss" },
		{ name: "Long-arm Centipede Giraffe", context: "Mini Boss" },
		{
			name: "Seven Ashina Spears",
			context: "Generic Enemy",
			reoccurring: true,
		},
		{ name: "General Naomori Kawarada", context: "Mini Boss" },
		{ name: "Blazing Bull", context: "Mini Boss" },
		{ name: "Headless Ape", context: "Boss" },
		{ name: "O'Rin of the Water", context: "Mini Boss" },
		{ name: "Ashina Reservoir", context: "Location" },
		{ name: "Senpou Temple", context: "Location" },
	],
};
