import type { GameSource } from "../types";

export const terraria: GameSource = {
	gameName: "Terraria",
	remarkPool: [
		"Knocked into lava",
		"Bad arena setup",
		"Ran out of potions",
		"Got walled",
		"No buffs prepped",
		"Bad dodge timing",
		"Underleveled gear",
		"Took contact damage",
	],
	groupTitlePool: ["Boss Rush", "Speed Progression"],
	profilePool: [
		{ name: "Main Playthrough" },
		{ name: "Master Mode Run" },
		{ name: "New World Seed" },
		{ name: "Multiplayer Server" },
		{ name: "Journey Mode Test" },
	],
	subjectPool: [
		{ name: "King Slime", context: "Boss" },
		{ name: "Eye of Cthulhu", context: "Boss" },
		{ name: "Eater of Worlds", context: "Boss" },
		{ name: "Queen Bee", context: "Boss" },
		{ name: "Skeletron", context: "Boss" },
		{ name: "Wall of Flesh", context: "Boss" },
		{ name: "The Twins", context: "Boss" },
		{ name: "The Destroyer", context: "Boss" },
		{ name: "Skeletron Prime", context: "Boss" },
		{ name: "Plantera", context: "Boss" },
		{ name: "Golem", context: "Boss" },
		{ name: "Duke Fishron", context: "Boss" },
		{ name: "Empress of Light", context: "Boss" },
		{ name: "Queen Slime", context: "Boss" },
		{ name: "Lunatic Cultist", context: "Boss" },
		{ name: "Moon Lord", context: "Boss" },
		{ name: "Zombie", context: "Generic Enemy", reoccurring: true },
		{ name: "Demon Eye", context: "Generic Enemy", reoccurring: true },
		{
			name: "World Feeder Segment",
			context: "Generic Enemy",
			reoccurring: true,
		},
		{ name: "Giant Worm", context: "Generic Enemy", reoccurring: true },
		{
			name: "Pirate Invasion",
			context: "Generic Enemy",
			reoccurring: true,
		},
		{ name: "Goblin Army", context: "Generic Enemy", reoccurring: true },
		{ name: "Frost Legion", context: "Generic Enemy", reoccurring: true },
		{
			name: "Old One's Army",
			context: "Generic Enemy",
			reoccurring: true,
		},
		{ name: "Dungeon Guardian", context: "Mini Boss" },
		{ name: "Wyvern", context: "Mini Boss" },
		{ name: "Dungeon", context: "Location" },
		{ name: "Underground Jungle", context: "Location" },
		{ name: "Ocean", context: "Location" },
	],
};
